name: MERN Stack Docker Build and Publish

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:  # Allows manual triggering

env:
  REGISTRY: docker.io
  DOCKERHUB_NAMESPACE: sheryarkayani

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_NAMESPACE }}/social-media
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      # Server (Backend)
      - name: Build and push Server
        uses: docker/build-push-action@v4
        with:
          context: ./Server
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.DOCKERHUB_NAMESPACE }}/social-media-server:latest
            ${{ env.REGISTRY }}/${{ env.DOCKERHUB_NAMESPACE }}/social-media-server:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.DOCKERHUB_NAMESPACE }}/social-media-server:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.DOCKERHUB_NAMESPACE }}/social-media-server:buildcache,mode=max

      # Client (Frontend)
      - name: Build and push Client
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.DOCKERHUB_NAMESPACE }}/social-media-client:latest
            ${{ env.REGISTRY }}/${{ env.DOCKERHUB_NAMESPACE }}/social-media-client:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.DOCKERHUB_NAMESPACE }}/social-media-client:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.DOCKERHUB_NAMESPACE }}/social-media-client:buildcache,mode=max